export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import BootstrapClient from '../components/BootstrapClient'
import 'bootstrap/dist/css/bootstrap.min.css'
import TopNavbar from '../components/TopNavbar'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
            <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Notes</title>
      </head>
      <body>
        <TopNavbar isLoggedIn={false} />
      <div className="bg-dark h-100" style={{minHeight: '100vh'}}>
                {children}
                <BootstrapClient />
              </div>
      </body>
    </html>
  )
}
