# Generated by Django 3.2.8 on 2023-02-11 10:55

from django.db import migrations, models
import django_resized.forms
import note.models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20221201_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='localmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=note.models.get_file_upload_path),
        ),
        migrations.AlterField(
            model_name='localmessage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1024, 1024], upload_to=note.models.get_image_upload_path),
        ),
        migrations.AlterField(
            model_name='localmessage',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
