# Generated by Django 3.2.8 on 2022-12-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='localmessage',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
