# Generated by Django 5.1.2 on 2024-11-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20241028_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localmessage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='localmessage',
            name='image',
        ),
    ]
