# Generated by Django 5.1.2 on 2025-02-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_create_initial_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='localmessagelist',
            name='show_in_feed',
            field=models.BooleanField(default=True),
        ),
    ]
