# Generated by Django 5.1.2 on 2025-02-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_localmessagelist_show_in_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='note.localmessage')),
            ],
        ),
    ]
