# Generated by Django 5.1.2 on 2025-07-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0012_note_chunksembedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localmessage',
            name='pinned',
        ),
        migrations.AddField(
            model_name='localmessage',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='noteembedding',
            name='note_id',
            field=models.IntegerField(unique=True),
        ),
    ]
