# Generated by Django 5.1.2 on 2025-12-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0015_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='localmessagelist',
            name='disable_related',
            field=models.BooleanField(default=False),
        ),
    ]
