# Generated by Django 5.2.8 on 2026-01-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0017_workspace_localmessagelist_workspaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localmessagelist',
            name='show_in_feed',
        ),
    ]
