# Generated by Django 5.2.8 on 2026-01-25 22:22

from django.db import migrations


def create_default_workspaces(apps, schema_editor):
    """Create default workspaces for existing users"""
    User = apps.get_model('auth', 'User')
    Workspace = apps.get_model('note', 'Workspace')
    LocalMessageList = apps.get_model('note', 'LocalMessageList')
    
    for user in User.objects.all():
        # Check if user already has a default workspace
        # Use a more defensive query to handle potential data corruption
        try:
            existing_default = Workspace.objects.filter(user=user, is_default=True).first()
        except (ValueError, TypeError):
            # If there's data corruption, skip this user or clean it up
            # Try to find workspaces that might belong to this user by other means
            existing_default = None
        
        if existing_default:
            continue
        
        # Get all categories for this user
        categories = LocalMessageList.objects.filter(user=user)
        
        if not categories.exists():
            continue
        
        # Create default workspace
        default_workspace_name = f"{user.username}'s Workspace"
        workspace = Workspace.objects.create(
            name=default_workspace_name,
            description='Default workspace containing all categories',
            user=user,
            is_default=True
        )
        
        # Assign all categories to the default workspace
        workspace.categories.set(categories)
        
        # Set a default category (first one or one named 'General', 'Main', etc.)
        default_category = None
        for category in categories:
            if category.name.lower() in ['general', 'main', 'default', 'notes']:
                default_category = category
                break
        
        if not default_category:
            default_category = categories.first()
        
        workspace.default_category = default_category
        workspace.save()


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0017_workspace_localmessagelist_workspaces'),
    ]

    operations = [
        migrations.RunPython(create_default_workspaces),
    ]
