# Generated by Django 5.2.8 on 2026-01-25 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0018_remove_localmessagelist_show_in_feed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localmessagelist',
            name='archived',
        ),
    ]
