# Generated by Django 5.2.8 on 2026-02-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0022_filecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
