# Generated by Django 5.2.8 on 2026-03-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0027_remove_reminder_is_snoozed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='last_dispatched',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
